name: release-main

on:
  release:
    types: [published]
    branches: [main]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
{% if cookiecutter.publish_to == "private_pypi" %}
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Export tag
        id: vars
        run: {% raw %}echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT{% endraw %}

      - name: Build
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build
        env:
          RELEASE_VERSION: {% raw %}${{ steps.vars.outputs.tag }}{% endraw %}

      - name: Publish to Private PyPI
        env:
          PRIVATE_PYPI_REPOSITORY_NAME: {% raw %}${{ vars.PRIVATE_PYPI_REPOSITORY_NAME }}{% endraw %}
        run: |
          source .venv/bin/activate
          poetry publish -r $PRIVATE_PYPI_REPOSITORY_NAME

{% endif %}
{%- if cookiecutter.mkdocs == "y" %}
  deploy-docs:
    {% if cookiecutter.publish_to == "private_pypi" -%}
    needs: publish
    {% endif -%}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Deploy documentation
        run: poetry run mkdocs gh-deploy --force
{% endif %}
