{% extends "./on-release-main.yml" %}

{% block publish %}
{%- raw -%}
      - name: Build
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          make build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.RELEASE_VERSION }}
      
      - name: Publish to CodeArtifact
        env:
          CODEARTIFACT_REPOSITORY_NAME: ${{ vars.CODEARTIFACT_REPOSITORY_NAME }}
        run: |
          source .venv/bin/activate
          poetry publish -r $CODEARTIFACT_REPOSITORY_NAME

{% endraw %}
{% endblock %}
